# Usar uma imagem slim para reduzir o tamanho
FROM openjdk:21-jdk-slim

# Definir diretório de trabalho
WORKDIR /app

# Adicionar e definir permissão para o jar da aplicação
COPY target/desafio3-0.0.1-SNAPSHOT.jar app.jar

# Expor a porta da aplicação (8081, por exemplo)
EXPOSE 8081

# Definir o ponto de entrada
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
